apiVersion: v1
kind: ReplicationController
metadata:
  name: abc-api-8080
spec:
  replicas: 3
  selector:
    app: abc-api-8080
    version: latest
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: abc-api-8080
        version: latest
      name: abc-api-8080
    spec:
      containers:
      - image: registry.odds.team/docker-registry/abc-api:latest
        imagePullPolicy: Always
        name: abc-api-8080
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: myregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
