apiVersion: v1
kind: Service
metadata:
  name: abc-api-clusterip-svc
  labels:
    app: abc-api-clusterip
spec:
  ports:
  - port: 80
  externalIPs:
  - 159.65.23.144
  selector:
    app: abc-api-clusterip
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: abc-api-clusterip-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: abc-api-clusterip
    spec:
      containers:
      - name: abc-api-clusterip-pod
        image: katacoda/docker-http-server
        ports:
        - containerPort: 80
